### ISSUE TITLE
Publish this as a PyPI package

### ISSUE THREAD

**Issue by OWissett** [liedllab/TopModel#2]
We are trying to publish a PyPI package which depends on this package, but PyPI does not allow for git dependancies in the `pyproject.toml`.

**Comment by janikkokot** [comment]
I will take a look into it and see what I can do.

**Comment by OWissett** [comment]
Thank you :)

**Comment by OWissett** [comment]
I think you'll need to call the package something else on PyPI since someone else has a package called topmodel already...

**Comment by OWissett** [comment]
Any progress?

**Comment by janikkokot** [comment]
The package should be up on pypi now under the name **protein-topmodel**, let me know if this works or wether you encounter any issues.
